"""empty message

Revision ID: 45867ec09b16
Revises: 091d1caddd99
Create Date: 2021-12-04 01:28:39.988802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45867ec09b16'
down_revision = '091d1caddd99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('firstname', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('lastname', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'lastname')
    op.drop_column('user', 'firstname')
    # ### end Alembic commands ###
