"""empty message

Revision ID: 4fde7539863c
Revises: f6745342a1a9
Create Date: 2021-12-06 21:25:31.420940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fde7539863c'
down_revision = 'f6745342a1a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'image')
    # ### end Alembic commands ###
