"""empty message

Revision ID: f6745342a1a9
Revises: 875717dcce6d
Create Date: 2021-12-04 15:30:50.605178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6745342a1a9'
down_revision = '875717dcce6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=64), nullable=True))
    op.drop_column('user', 'firstname')
    op.drop_column('user', 'lastname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('lastname', sa.VARCHAR(length=64), nullable=True))
    op.add_column('user', sa.Column('firstname', sa.VARCHAR(length=64), nullable=True))
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
